name: demo
login: user@example.com
password: secret
min_seconds_between_bids: 3
max_seconds_between_bids: 6
follow_up_delay_minutes: 5
filters:
  categories: ["Юриспруденция"]
  types: ["Доклад", "Статья"]
  min_budget: 500
message_templates:
  - name: "base"
    text: "Здравствуйте! Готов выполнить заказ качественно и в срок."
    delay_seconds: 0
  - name: "followup"
    text: "Хотел уточнить, готовы ли обсудить детали заказа?"
    delay_seconds: 600
headless: false
